dump and restore binaries functional

diff --git a/bin/dump-structure b/bin/dump-structure
--- a/bin/dump-structure
+++ b/bin/dump-structure
@@ -1,8 +1,9 @@
 #!/bin/sh
 echo "Creating class migrations... "
-retval=`php vendor/tpetb/pimcore-sak/src/MigrateCommit.php; echo $?`
-if [ $retval -ne 0 ]; then
-        echo "Migration failed.";
-        exit $retval;
+retval=`php vendor/tpetb/pimcore-sak/src/MigrateCommit.php;`
+if [ $retval ]; then
+        echo "Migration failed. PHP Output:";
+        echo $retval;
+        exit 1
 fi
 echo "Done.\n"
